#!/bin/sh
# usage: undaemonize <command> [args]

"$@" || exit $?
PID=$(pgrep -fn "^$*$")
if [ "$PID" ]; then
  for i in `seq 1 15`; do
    trap "kill -s $i $PID; wait \$!" $i
  done
  tail --pid=$PID -f /dev/null & wait $!
fi
